<<<<<<< HEAD:src/app/layout.js
import './globals.css'
import { Inter } from 'next/font/google'
=======
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
>>>>>>> 368880244276bc8683fd39627e73bae57a4f44b8:src/app/layout.tsx

const inter = Inter({ subsets: ["latin"] });

<<<<<<< HEAD:src/app/layout.js
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
=======
export const metadata: Metadata = {
	title: "JEVC ",
	description: "Portfolio of JEVC",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
>>>>>>> 368880244276bc8683fd39627e73bae57a4f44b8:src/app/layout.tsx
}
